[2025-01-26T22:05:07.876+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T22:05:07.924+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_gener_data.stg-load scheduled__2025-01-26T22:04:00+00:00 [queued]>
[2025-01-26T22:05:07.945+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_gener_data.stg-load scheduled__2025-01-26T22:04:00+00:00 [queued]>
[2025-01-26T22:05:07.945+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-26T22:05:07.983+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): stg-load> on 2025-01-26 22:04:00+00:00
[2025-01-26T22:05:07.999+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1607) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-26T22:05:08.002+0000] {standard_task_runner.py:72} INFO - Started process 1609 to run task
[2025-01-26T22:05:08.003+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_gener_data', 'stg-load', 'scheduled__2025-01-26T22:04:00+00:00', '--job-id', '405', '--raw', '--subdir', 'DAGS_FOLDER/DAG_test_data.py', '--cfg-path', '/tmp/tmp9qnoqor1']
[2025-01-26T22:05:08.008+0000] {standard_task_runner.py:105} INFO - Job 405: Subtask stg-load
[2025-01-26T22:05:08.136+0000] {task_command.py:467} INFO - Running <TaskInstance: load_gener_data.stg-load scheduled__2025-01-26T22:04:00+00:00 [running]> on host a664bcf281bf
[2025-01-26T22:05:08.805+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_gener_data' AIRFLOW_CTX_TASK_ID='stg-load' AIRFLOW_CTX_EXECUTION_DATE='2025-01-26T22:04:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-26T22:04:00+00:00'
[2025-01-26T22:05:08.807+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T22:05:08.914+0000] {base.py:84} INFO - Retrieving connection 'DB_connect'
[2025-01-26T22:05:08.993+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-26T22:05:09.020+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T22:05:09.021+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=load_gener_data, task_id=stg-load, run_id=scheduled__2025-01-26T22:04:00+00:00, execution_date=20250126T220400, start_date=20250126T220507, end_date=20250126T220509
[2025-01-26T22:05:09.119+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-26T22:05:09.186+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-26T22:05:09.189+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
