[2025-01-31T21:32:09.359+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-31T21:32:09.428+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_gener_data.stg-load scheduled__2025-01-31T21:31:00+00:00 [queued]>
[2025-01-31T21:32:09.453+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_gener_data.stg-load scheduled__2025-01-31T21:31:00+00:00 [queued]>
[2025-01-31T21:32:09.454+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-31T21:32:09.505+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): stg-load> on 2025-01-31 21:31:00+00:00
[2025-01-31T21:32:09.524+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2811) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-31T21:32:09.530+0000] {standard_task_runner.py:72} INFO - Started process 2817 to run task
[2025-01-31T21:32:09.540+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_gener_data', 'stg-load', 'scheduled__2025-01-31T21:31:00+00:00', '--job-id', '624', '--raw', '--subdir', 'DAGS_FOLDER/DAG_test_data.py', '--cfg-path', '/tmp/tmp0i5ij8d0']
[2025-01-31T21:32:09.547+0000] {standard_task_runner.py:105} INFO - Job 624: Subtask stg-load
[2025-01-31T21:32:09.712+0000] {task_command.py:467} INFO - Running <TaskInstance: load_gener_data.stg-load scheduled__2025-01-31T21:31:00+00:00 [running]> on host a664bcf281bf
[2025-01-31T21:32:10.334+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_gener_data' AIRFLOW_CTX_TASK_ID='stg-load' AIRFLOW_CTX_EXECUTION_DATE='2025-01-31T21:31:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-31T21:31:00+00:00'
[2025-01-31T21:32:10.337+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-31T21:32:10.594+0000] {base.py:84} INFO - Retrieving connection 'DB_connect'
[2025-01-31T21:32:10.667+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-31T21:32:10.693+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-31T21:32:10.694+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=load_gener_data, task_id=stg-load, run_id=scheduled__2025-01-31T21:31:00+00:00, execution_date=20250131T213100, start_date=20250131T213209, end_date=20250131T213210
[2025-01-31T21:32:10.766+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-31T21:32:10.809+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-31T21:32:10.812+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
