[2025-01-26T22:08:09.382+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T22:08:09.439+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_processing.nds-load scheduled__2025-01-26T22:06:00+00:00 [queued]>
[2025-01-26T22:08:09.463+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_processing.nds-load scheduled__2025-01-26T22:06:00+00:00 [queued]>
[2025-01-26T22:08:09.463+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-26T22:08:09.529+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): nds-load> on 2025-01-26 22:06:00+00:00
[2025-01-26T22:08:09.547+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1718) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-26T22:08:09.550+0000] {standard_task_runner.py:72} INFO - Started process 1722 to run task
[2025-01-26T22:08:09.552+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_processing', 'nds-load', 'scheduled__2025-01-26T22:06:00+00:00', '--job-id', '426', '--raw', '--subdir', 'DAGS_FOLDER/DAG_etl.py', '--cfg-path', '/tmp/tmpp1x081gn']
[2025-01-26T22:08:09.557+0000] {standard_task_runner.py:105} INFO - Job 426: Subtask nds-load
[2025-01-26T22:08:09.697+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_processing.nds-load scheduled__2025-01-26T22:06:00+00:00 [running]> on host a664bcf281bf
[2025-01-26T22:08:10.424+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_processing' AIRFLOW_CTX_TASK_ID='nds-load' AIRFLOW_CTX_EXECUTION_DATE='2025-01-26T22:06:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-26T22:06:00+00:00'
[2025-01-26T22:08:10.426+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T22:08:10.500+0000] {base.py:84} INFO - Retrieving connection 'DB_connect'
[2025-01-26T22:08:10.555+0000] {base.py:84} INFO - Retrieving connection 'DB_connect'
[2025-01-26T22:08:10.673+0000] {base.py:84} INFO - Retrieving connection 'DB_connect'
[2025-01-26T22:08:10.814+0000] {base.py:84} INFO - Retrieving connection 'DB_connect'
[2025-01-26T22:08:10.965+0000] {base.py:84} INFO - Retrieving connection 'DB_connect'
[2025-01-26T22:08:11.107+0000] {base.py:84} INFO - Retrieving connection 'DB_connect'
[2025-01-26T22:08:11.226+0000] {base.py:84} INFO - Retrieving connection 'DB_connect'
[2025-01-26T22:08:11.347+0000] {base.py:84} INFO - Retrieving connection 'DB_connect'
[2025-01-26T22:08:11.521+0000] {base.py:84} INFO - Retrieving connection 'DB_connect'
[2025-01-26T22:08:11.671+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-26T22:08:11.702+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T22:08:11.703+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_processing, task_id=nds-load, run_id=scheduled__2025-01-26T22:06:00+00:00, execution_date=20250126T220600, start_date=20250126T220809, end_date=20250126T220811
[2025-01-26T22:08:11.798+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-26T22:08:11.904+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-26T22:08:12.008+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
